{% set version = "7.0.0" %}


package:
  name: superlu
  version: {{ version }}

source:
  url: https://github.com/xiaoyeli/superlu/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d7b91d4e0bb52644ca74c1a4dd466a694ddf1244a7bbf93cb453e8ca1f6527eb

build:
  number: 0
  skip: true  # [win]
  features:

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
    - libblas
    - libcblas
  run:

test:
  commands:
    - test ! -f ${PREFIX}/lib/libsuperlu.a
    - test -f ${PREFIX}/lib/libsuperlu${SHLIB_EXT}

about:
  home: http://crd-legacy.lbl.gov/~xiaoye/SuperLU/
  license: BSD-3-Clause
  license_file: License.txt
  summary: |
    Supernodal LU: solvers for large, sparse, nonsymmetric systems of linear
    equations.

extra:
  recipe-maintainers:
    - grlee77
    - minrk
